server:
  port: 6671

spring:
  application:
    name: redis-server
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
#      defaultZone: http://localhost:6670/eureka/  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
      defaultZone: http://${eureka:localhost}/eureka/  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
  instance:
    instance-id: spring-cloud-redis-server #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址