services:
  db:
    build:
      ./data
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: cloud_demo


  redis:
    image: "redis:alpine3.8"
    ports:
      - 6379:6379

  cloud-server:
    build: ./CloudServer
    ports:
      - "6670:6670"

  redis-server:
    build: ./RedisDemo
    ports:
      - "6671:6671"
    environment:
      EUREKA_ADDR: cloud-server
      EUREKA_PORT: 6379
    depends_on:
      - redis
      - cloud-server

  mysql-server:
    build: ./MysqlDemo/
    ports:
      - 6669:6669
    environment:
      EUREKA_ADDR: cloud-server
      EUREKA_PORT: 6379
      MYSQL_ADDR: db
      MYSQL_PORT: 3307
      MYSQL_PASSWORD: cloud_demo
    depends_on:
      - cloud-server
      - db
