server:
  port: 6668
spring:
  applicaiton:
    name: RabbitMQDemo
  rabbitmq:
    host: 192.168.25.192
    port: 5672
    username: aep-dev
    password: Quectel@2021
    virtual-host: aep-dev-vhost
    queue: kiritQueue
    exchange: my_exchange
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: false
          max-attempts: 5
          initial-interval: 3000